POST https://localhost:8000 HTTP/1.1
Content-Type: application/json

{
  "name": "Test User RDO",
  "email": "pro_user@test.loc",
  "avatarUrl": "/some/user/avatar.jpg",
  "password": "12848",
  "isPro": true,
  "favoriteOffers": [],
}
