# Пользователь

## Авторизация пользователя
POST http://localhost:8000/users/login HTTP/1.1
Content-Type: application/json

{
   "email": "ironman@stark-industries.loc",
   "password": "IlonMask123"
}

###

## Логаут пользователя
GET http://localhost:8000/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ4NzM1MTM0ZmQ3N2NkMzI5Y2RjNTgiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6IkQ6XFxPcGVuU2VydmVyXFxkb21haW5zXFxzaXgtY2l0aWVzLm5vZGUubG9jXFx1cGxvYWRcXHVzZXItYXZhdGFyLnJRZHpYYVBULURNM2pFcDlHS2FUOC5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZDg3M2VlMzRmZDc3Y2QzMjljZGM1ZCJdLCJleHAiOjE3MDk1NTM3MzYsImlhdCI6MTcwOTM4MDkzNn0.NW8-fLG_I7u3ZGdrUghZ9xUOjjBn_43Bpc5-q4zO70U

###

## Проверка статуса авторизации
GET http://localhost:8000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ4NzM1MTM0ZmQ3N2NkMzI5Y2RjNTgiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6IkQ6XFxPcGVuU2VydmVyXFxkb21haW5zXFxzaXgtY2l0aWVzLm5vZGUubG9jXFx1cGxvYWRcXHVzZXItYXZhdGFyLnJRZHpYYVBULURNM2pFcDlHS2FUOC5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZDg3M2VlMzRmZDc3Y2QzMjljZGM1ZCJdLCJleHAiOjE3MDk1NTM3MzYsImlhdCI6MTcwOTM4MDkzNn0.NW8-fLG_I7u3ZGdrUghZ9xUOjjBn_43Bpc5-q4zO70U

{
   "email": "ironman@stark-industries.loc"
}

###

## Создание нового пользователя
POST http://localhost:8000/users/register HTTP/1.1
Content-Type: application/json

{
   "name": "Robert Downey",
   "email": "ironman@stark-industries.loc",
   "avatarUrl": "/some/user/avatar.jpg",
   "password": "IlonMask123",
   "isPro": true,
   "favoriteOffers": [
      "65c3539f177a2ad3d529f00c",
      "65c3539f177a2ad3d529f01c"
    ]
}

###

## Загрузка аватарки для пользоваетля
POST http://localhost:8000/users/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ4NzM1MTM0ZmQ3N2NkMzI5Y2RjNTgiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6InVzZXItYXZhdGFyLnJRZHpYYVBULURNM2pFcDlHS2FUOC5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZDg3M2VlMzRmZDc3Y2QzMjljZGM1ZCIsIjY1ZDg3NDEzMzRmZDc3Y2QzMjljZGM1ZiJdLCJleHAiOjE3MDk2NTk4NzQsImlhdCI6MTcwOTQ4NzA3NH0.yY98CxtVmTPDgoMwVp1IarYsQxWozOCeBoG4SSdcYHY

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user-avatar"; filename="avatar-max.jpg"
Content-Type: image/jpeg

< D:\OpenServer\domains\six-cities.node.loc\markup\img\avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Получение списка избранных предложений для пользователя
GET http://localhost:8000/users/favorites/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ4NzM1MTM0ZmQ3N2NkMzI5Y2RjNTgiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6IkQ6XFxPcGVuU2VydmVyXFxkb21haW5zXFxzaXgtY2l0aWVzLm5vZGUubG9jXFx1cGxvYWRcXHVzZXItYXZhdGFyLnJRZHpYYVBULURNM2pFcDlHS2FUOC5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZDg3M2VlMzRmZDc3Y2QzMjljZGM1ZCJdLCJleHAiOjE3MDk1NTM3MzYsImlhdCI6MTcwOTM4MDkzNn0.NW8-fLG_I7u3ZGdrUghZ9xUOjjBn_43Bpc5-q4zO70U

###

## Добавление предложения в избранное
POST http://localhost:9000/users/favorites/65d8741334fd77cd329cdc5f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ4NzM1MTM0ZmQ3N2NkMzI5Y2RjNTgiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6IkQ6XFxPcGVuU2VydmVyXFxkb21haW5zXFxzaXgtY2l0aWVzLm5vZGUubG9jXFx1cGxvYWRcXHVzZXItYXZhdGFyLnJRZHpYYVBULURNM2pFcDlHS2FUOC5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZDg3M2VlMzRmZDc3Y2QzMjljZGM1ZCJdLCJleHAiOjE3MDk1NTM3MzYsImlhdCI6MTcwOTM4MDkzNn0.NW8-fLG_I7u3ZGdrUghZ9xUOjjBn_43Bpc5-q4zO70U

###

## Удаление предложения из избранного
DELETE  http://localhost:8000/users/favorites/65d8741334fd77cd329cdc5f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ4NzM1MTM0ZmQ3N2NkMzI5Y2RjNTgiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6IkQ6XFxPcGVuU2VydmVyXFxkb21haW5zXFxzaXgtY2l0aWVzLm5vZGUubG9jXFx1cGxvYWRcXHVzZXItYXZhdGFyLnJRZHpYYVBULURNM2pFcDlHS2FUOC5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZDg3M2VlMzRmZDc3Y2QzMjljZGM1ZCJdLCJleHAiOjE3MDk1NTM3MzYsImlhdCI6MTcwOTM4MDkzNn0.NW8-fLG_I7u3ZGdrUghZ9xUOjjBn_43Bpc5-q4zO70U
