# Предложения

## Список предложений
GET http://localhost:8000/offers/ HTTP/1.1

###

## Список предложений с лимитом
GET http://localhost:8000/offers/?limit=2 HTTP/1.1

###

## Детальная информация о конкретном предолжении
GET http://localhost:8000/offers/65c3539f177a2ad3d529f01c HTTP/1.1

###


## Получение списка премиальных предложений для города
GET http://localhost:8000/offers/premium/Cologne HTTP/1.1

###

## Изменение статуса "Избранное" у предложения
PATCH  http://localhost:8000/offers/favorites/65c3539f177a2ad3d529f01c/1 HTTP/1.1

###

## Получение списка избранных предложений для пользователя
GET http://localhost:8000/offers/favorites/65c3539f177a2ad3d529efff HTTP/1.1

###

## Создание предолжения
POST http://localhost:8000/offers/ HTTP/1.1
Content-Type: application/json

{
  "name": "Comfortable A-frame in mountines",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam enim quam, mollis vel suscipit et, venenatis a nulla. Integer vitae aliquam lacus. Vivamus semper leo nec bibendum malesuada. Morbi ligula velit, facilisis a vulputate vitae, malesuada sit amet massa. Praesent sed molestie lectus, vitae dignissim nulla. Maecenas sollicitudin in justo sed venenatis. Duis congue arcu quis iaculis molestie. Mauris lobortis imperdiet sem facilisis elementum. Proin ullamcorper leo in ultrices pretium. Curabitur ultricies vel nulla eu laoreet. Pellentesque id lectus nec justo tempus bibendum. Nulla facilisi. Phasellus scelerisque est at est varius bibendum. Vestibulum eget mauris gravida, imperdiet sapien a, bibendum.",
  "date": "2024-02-07T09:55:28.801Z",
  "city": "Dusseldorf",
  "previewImage": "/some/photo/preview1.jpg;",
  "images": [
    "photo4.jpg",
    "photo5.jpg",
    "photo6.jpg",
    "photo7.jpg",
    "photo8.jpg",
    "photo9.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "rating": 1,
  "type": "house",
  "rooms": 0,
  "guests": 10,
  "price": 99999,
  "facilities": [
    "Towels",
    "friendly workspace",
    "Air conditioning",
    "Breakfast"
  ],
  "userId": "65c3539f177a2ad3d529f005",
  "commentCount": 0,
  "coordinates": {
    "latitude": "52.370216",
    "longitude": "4.895168"
  }
}

###

## Обновление предложения
PATCH http://localhost:8000/offers/65c3539f177a2ad3d529f002 HTTP/1.1
Content-Type: application/json

{
  "images": [
    "photo1.jpg",
    "photo2.jpg",
    "photo3.jpg",
    "photo4.jpg",
    "photo5.jpg"
  ]
}

###

## Удаление предложения и комментариев к нему
DELETE http://localhost:8000/offers/65c3539f177a2ad3d529f012 HTTP/1.1

