# Комментарии

## Созодание нового комментария
POST http://localhost:8000/comments/ HTTP/1.1
Content-Type: application/json

{
  "text": "Comment text. Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  "rating": 5,
  "userId": "65d5f4b362d59fcfd03cd80b",
  "offerId": "65cf1f6d7757251173e040c1"
}

###

## Получение списка комментариев для предложения
GET http://localhost:8000/comments/65cf1f6d7757251173e040c1/ HTTP/1.1

###
