# Комментарии

## Созодание нового комментария
POST http://localhost:8000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI2NWQ1ZjRiMzYyZDU5ZmNmZDAzY2Q4MGIiLCJuYW1lIjoiUm9iZXJ0IERvd25leSIsImVtYWlsIjoiaXJvbm1hbkBzdGFyay1pbmR1c3RyaWVzLmxvYyIsImF2YXRhclVybCI6InVzZXItYXZhdGFyLmszVjRVU0ZiX18xdVNNbG5kdjNvMy5qcGVnIiwiaXNQcm8iOnRydWUsImZhdm9yaXRlT2ZmZXJzIjpbIjY1ZTU5N2I3OWU3MTc0MDE5ZTY5YzAwMSJdLCJleHAiOjE3MDk3MzcxODEsImlhdCI6MTcwOTU2NDM4MX0.TAmEO9PuDHHGkW-AA_zScCOOCM3uX6QHlLJSBNWEiNA

{
  "text": "Comment text. Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  "rating": 5,
  "offerId": "65e597b79e7174019e69c001"
}

###

## Получение списка комментариев для предложения
GET http://localhost:8000/comments/65c3539f177a2ad3d529f01c HTTP/1.1

###
